# Generated by Django 5.1.2 on 2024-10-30 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_banner_created_alter_exam_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='default_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.course'),
        ),
    ]
