# Generated by Django 5.1.2 on 2024-11-06 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_talenthunt_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprogress',
            name='completed_on',
        ),
        migrations.AddField(
            model_name='level',
            name='duration',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='talenthunt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_talentHunt', to='dashboard.talenthunt'),
            preserve_default=False,
        ),
    ]
