# Generated by Django 5.1.2 on 2024-11-08 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_studentprogress_talenthunt'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprogress',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_level', to='dashboard.level'),
        ),
    ]
