# Generated by Django 5.1.2 on 2024-11-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_studentprogress_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprogressdetail',
            name='selected_option',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
