# Generated by Django 5.1.2 on 2024-11-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_studentprogressdetail_selected_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='exam_images/'),
        ),
    ]
