# Generated by Django 5.1.2 on 2024-11-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_exam_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprogressdetail',
            name='answerd',
            field=models.BooleanField(default=True),
        ),
    ]
