# Generated by Django 5.1.2 on 2024-11-13 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_studentprogressdetail_answerd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprogressdetail',
            old_name='answerd',
            new_name='answered',
        ),
    ]
