# Generated by Django 5.1.2 on 2024-11-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_rename_answerd_studentprogressdetail_answered'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='m3u8',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
