# Generated by Django 5.1.2 on 2024-11-22 05:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_video_m3u8_alter_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='m3u8',
        ),
        migrations.CreateModel(
            name='M3U8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True, null=True)),
                ('is_downloadable', models.BooleanField(default=False)),
                ('is_free', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m3u8videos', to='dashboard.lesson')),
            ],
        ),
    ]
