# Generated by Django 5.1.2 on 2024-11-25 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_remove_video_m3u8_m3u8'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchlesson',
            name='folder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.folder'),
            preserve_default=False,
        ),
    ]
