# Generated by Django 5.1.2 on 2024-11-25 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_batchlesson_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchlesson',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.folder'),
        ),
        migrations.AlterField(
            model_name='batchlesson',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.lesson'),
        ),
    ]
