# Generated by Django 5.1.2 on 2024-11-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_batchlesson_folder_alter_batchlesson_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='m3u8',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='M3U8',
        ),
    ]
