# Generated by Django 5.1.2 on 2024-11-29 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_video_m3u8_delete_m3u8'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='m3u8',
            new_name='is_m3u8',
        ),
    ]
