# Generated by Django 5.1.2 on 2024-11-29 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_video_m3u8'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='is_free',
            new_name='m3u8_is_downloadable',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='is_m3u8',
            new_name='m3u8_is_free',
        ),
    ]
