# Generated by Django 5.1.2 on 2024-11-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_rename_is_free_video_m3u8_is_downloadable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
