# Generated by Django 5.1.2 on 2024-12-04 04:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_video_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
