# Generated by Django 5.1.2 on 2024-12-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_exam_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'No Special Access'), (1, 'Admin')], default=0),
        ),
    ]
