# Generated by Django 5.1.2 on 2024-12-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_currentaffairs_pdfnote_current_affairs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='current_affairs',
        ),
        migrations.RemoveField(
            model_name='pdfnote',
            name='current_affairs',
        ),
        migrations.AddField(
            model_name='pdfnote',
            name='current_affair',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='current_affair',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='CurrentAffairs',
        ),
    ]
