# Generated by Django 5.1.2 on 2024-12-07 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_remove_video_current_affairs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfnote',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdf_notes', to='dashboard.lesson'),
        ),
        migrations.AlterField(
            model_name='video',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='dashboard.lesson'),
        ),
    ]
