# Generated by Django 5.1.2 on 2024-12-07 05:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_alter_pdfnote_lesson_alter_video_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentAffairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='currentaffairs_images/')),
                ('is_free', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='pdfnote',
            name='currentaffair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currentaffair_pdf_notes', to='dashboard.lesson'),
        ),
        migrations.AddField(
            model_name='video',
            name='currentaffair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currentaffair_videos', to='dashboard.lesson'),
        ),
    ]
