# Generated by Django 5.1.2 on 2024-12-07 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_currentaffairs_pdfnote_currentaffair_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfnote',
            name='currentaffair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currentaffair_pdf_notes', to='dashboard.currentaffairs'),
        ),
        migrations.AlterField(
            model_name='video',
            name='currentaffair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currentaffair_videos', to='dashboard.currentaffairs'),
        ),
    ]
