# Generated by Django 5.1.2 on 2024-12-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_alter_pdfnote_currentaffair_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'No Special Access'), (1, 'Admin'), (2, 'Content manager'), (3, 'Admission manager')], default=0),
        ),
    ]
