# Generated by Django 5.1.2 on 2024-12-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation_description',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation_image',
            field=models.ImageField(blank=True, null=True, upload_to='explanation_images/'),
        ),
    ]
