# Generated by Django 5.1.2 on 2025-01-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_question_explanation_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='tp_stream',
            field=models.URLField(blank=True, null=True),
        ),
    ]
