# Generated by Django 5.1.2 on 2025-01-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_video_tp_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='tp_stream',
            field=models.CharField(blank=True, null=True),
        ),
    ]
