# Generated by Django 5.1.2 on 2025-02-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_alter_video_tp_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='mark',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
