# Generated by Django 5.1.2 on 2025-03-25 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_alter_question_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.chapter'),
        ),
        migrations.AddField(
            model_name='exam',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.folder'),
        ),
    ]
