# Generated by Django 5.1.2 on 2025-05-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_exam_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='number_of_attempt',
            field=models.IntegerField(default=1),
        ),
    ]
