# Generated by Django 5.1.2 on 2025-05-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_videopause'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_shuffle',
            field=models.BooleanField(default=False),
        ),
    ]
