# Generated by Django 5.1.2 on 2025-05-15 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_videorating'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='current_affair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.currentaffairs'),
        ),
    ]
