# Generated by Django 5.1.2 on 2025-05-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_exam_current_affair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'No Special Access'), (1, 'Admin'), (2, 'Content manager'), (3, 'Admission manager'), (4, 'Mentor')], default=0),
        ),
    ]
