# Generated by Django 5.1.2 on 2025-05-26 07:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_batchmentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='batches',
            field=models.ManyToManyField(blank=True, related_name='notifications', to='dashboard.batch'),
        ),
        migrations.AddField(
            model_name='notification',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='notifications', to='dashboard.course'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('all', 'All Users'), ('course', 'Course-wise'), ('batch', 'Batch-wise'), ('student', 'Selected Students')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='targeted_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
