# Generated by Django 5.1.2 on 2025-05-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0052_feepaymentplan_hdfcpaymentconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepaymentplan',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10),
        ),
    ]
