# Generated by Django 5.1.2 on 2025-05-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_feepaymentplan_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='hdfcpaymentconfig',
            name='api_key',
            field=models.CharField(blank=True, help_text='HDFC API Key', max_length=100, null=True),
        ),
    ]
