# Generated by Django 5.1.2 on 2025-05-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0054_hdfcpaymentconfig_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='hdfcpaymentconfig',
            name='payment_page_client_id',
            field=models.CharField(blank=True, help_text='HDFC Payment Page Client ID', max_length=100, null=True),
        ),
    ]
