# Generated by Django 5.1.2 on 2025-05-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_hdfcpaymentconfig_payment_page_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hdfcpaymentconfig',
            name='access_code',
            field=models.CharField(blank=True, help_text='HDFC Access Code', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hdfcpaymentconfig',
            name='merchant_id',
            field=models.CharField(blank=True, help_text='HDFC Merchant ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hdfcpaymentconfig',
            name='working_key',
            field=models.CharField(blank=True, help_text='HDFC Working Key for encryption', max_length=100, null=True),
        ),
    ]
