# Generated by Django 5.1.2 on 2025-05-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0056_alter_hdfcpaymentconfig_access_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment_link_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
