# Generated by Django 5.1.2 on 2025-05-29 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0057_paymenttransaction_payment_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('request_data', models.JSONField(default=dict)),
                ('headers', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('signature_valid', models.BooleanField(blank=True, help_text='Whether signature validation passed', null=True)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('INVALID', 'Invalid')], default='RECEIVED', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.paymenttransaction')),
            ],
            options={
                'verbose_name': 'Webhook Log',
                'verbose_name_plural': 'Webhook Logs',
                'ordering': ['-created'],
            },
        ),
    ]
