# Generated by Django 5.1.2 on 2025-05-29 10:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0058_webhooklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='transaction_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
