# Generated by Django 5.1.2 on 2025-05-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0059_paymenttransaction_transaction_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='hdfcpaymentconfig',
            name='webhook_custom_headers',
            field=models.JSONField(blank=True, default=dict, help_text='Custom headers for webhook authentication'),
        ),
        migrations.AddField(
            model_name='hdfcpaymentconfig',
            name='webhook_password',
            field=models.CharField(blank=True, help_text='Password for Basic Auth webhook authentication', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hdfcpaymentconfig',
            name='webhook_url',
            field=models.URLField(blank=True, help_text='URL where SmartGateway will send webhook events', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hdfcpaymentconfig',
            name='webhook_username',
            field=models.CharField(blank=True, help_text='Username for Basic Auth webhook authentication', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='event_type',
            field=models.CharField(blank=True, help_text='Type of webhook event', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hdfcpaymentconfig',
            name='webhook_secret',
            field=models.CharField(blank=True, help_text='Secret for additional webhook signature verification', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='webhooklog',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('INVALID', 'Invalid'), ('DUPLICATE', 'Duplicate')], default='RECEIVED', max_length=20),
        ),
    ]
