# Generated by Django 5.1.2 on 2025-05-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0060_hdfcpaymentconfig_webhook_custom_headers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepaymentplan',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('custom_date', 'Custom Date'), ('batch_duration', 'Batch Duration')], default='monthly', max_length=150),
        ),
    ]
