# Generated by Django 5.1.2 on 2025-06-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0061_alter_feepaymentplan_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooklog',
            name='webhook_date',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the webhook was created by SmartGateway', null=True),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='webhook_id',
            field=models.CharField(blank=True, db_index=True, help_text='Unique ID of the webhook event from SmartGateway', max_length=100, null=True),
        ),
    ]
