# Generated by Django 5.1.2 on 2025-06-13 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0063_notification_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='installments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installment_notifications', to='dashboard.feeinstallment'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('all', 'All Users'), ('course', 'Course-wise'), ('batch', 'Batch-wise'), ('student', 'Selected Students'), ('payment', 'Payment')], default='all', max_length=20),
        ),
    ]
