# Generated by Django 5.1.2 on 2025-06-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0064_notification_installments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('all', 'All Users'), ('course', 'Course-wise'), ('batch', 'Batch-wise'), ('student', 'Selected Students')], default='all', max_length=20),
        ),
    ]
