# Generated by Django 5.1.2 on 2025-06-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0065_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='old_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='old_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='currentaffairs',
            name='old_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='old_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exam',
            name='old_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='folder',
            name='old_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lesson',
            name='old_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='old_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pdfnote',
            name='old_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='old_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='old_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='talenthunt',
            name='old_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='old_id',
            field=models.IntegerField(default=0),
        ),
    ]
