# Generated by Django 5.1.2 on 2025-06-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0067_alter_banner_image_alter_chapter_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='folder',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
