# Generated by Django 5.1.2 on 2025-06-25 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0068_chapter_order_course_order_folder_order_lesson_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='order',
        ),
    ]
