# Generated by Django 5.1.2 on 2025-06-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0070_alter_video_m3u8_alter_video_tp_stream_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Model', 'Model'), ('Live', 'Live')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
