# Generated by Django 5.1.2 on 2025-06-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0071_exam_end_date_exam_exam_type_exam_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='visible_in_days',
            field=models.IntegerField(default=0),
        ),
    ]
