# Generated by Django 5.1.2 on 2025-07-25 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0072_folder_visible_in_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='district',
            field=models.CharField(choices=[('0', 'Andhra Pradesh'), ('1', 'Arunachal Pradesh'), ('2', 'Assam'), ('3', 'Bihar'), ('4', 'Chhattisgarh'), ('5', 'Goa'), ('6', 'Gujarat'), ('7', 'Haryana'), ('8', 'Himachal Pradesh'), ('9', 'Jharkhand'), ('10', 'Karnataka'), ('11', 'Kerala'), ('12', 'Madhya Pradesh'), ('13', 'Maharashtra'), ('14', 'Manipur'), ('15', 'Meghalaya'), ('16', 'Mizoram'), ('17', 'Nagaland'), ('18', 'Odisha'), ('19', 'Punjab'), ('20', 'Rajasthan'), ('21', 'Sikkim'), ('22', 'Tamil Nadu'), ('23', 'Telangana')], max_length=2),
        ),
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='dashboard.subject'),
        ),
    ]
