# Generated by Django 5.1.2 on 2025-08-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0075_slot_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Malayalam', 'Malayalam')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprogressdetail',
            name='time_taken',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
