# Generated by Django 5.1.2 on 2025-11-20 14:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0076_course_language_studentprogressdetail_time_taken'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorpayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.CharField(help_text='Razorpay Key ID', max_length=100)),
                ('key_secret', models.CharField(help_text='Razorpay Key Secret', max_length=100)),
                ('webhook_secret', models.CharField(blank=True, help_text='Razorpay Webhook Secret', max_length=100, null=True)),
                ('is_production', models.BooleanField(default=False, help_text='Use production environment')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='HDFCPaymentConfig',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Malayalam', 'Malayalam')], default='Malayalam', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='batch',
            field=models.ManyToManyField(blank=True, to='dashboard.batch'),
        ),
        migrations.AlterField(
            model_name='webhooklog',
            name='event_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='webhooklog',
            name='signature_valid',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webhooklog',
            name='webhook_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webhooklog',
            name='webhook_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
