# Generated by Django 5.1.2 on 2025-12-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0077_razorpayconfig_delete_hdfcpaymentconfig_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(blank=True, choices=[('Monthly', 'Monthly'), ('Scholarship', 'Scholarship')], max_length=255, null=True),
        ),
    ]
