# Generated by Django 5.1.2 on 2025-12-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0078_alter_exam_exam_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(blank=True, choices=[('Scholarship', 'Scholarship'), ('Model', 'Model')], max_length=255, null=True),
        ),
    ]
