# Generated by Django 5.1.2 on 2025-12-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0080_exam_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='total_marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
