# Generated by Django 5.1.2 on 2025-12-20 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0081_exam_total_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='total_marks',
        ),
    ]
